name: Pylint

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install dotenv
    - name: Load Secrets from GitHub
      env:
          DB_USER: ${{ secrets.TEST_SECRET_1 }}
          DB_PASS: ${{ secrets.TEST_SECRET_2 }}
      run: |
          echo "DB_USER is set $DB_USER"
          echo "DB_PASS is set $DB_PASS"
    - name: Run program
      run: python printex.py
      env : 
          DB_USER: ${{ secrets.TEST_SECRET_1 }}
          DB_PASS: ${{ secrets.TEST_SECRET_2 }}
    



