name: Pylint

on: 
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Test secrets
      run: |
        if [[ -z "$DUMMY" ]]; then
        echo "❌ Secret is empty!"
        else
        echo "✅ Secret is set!"
        fi
      env: 
        DUMMY: ${{ secrets.DUMMY_SECRET }}
    
    - name: Run program
      run: python printex.py
      env : 
        DUMMYY: ${{ secrets.DUMMY_SECRET }}
