name: Python Virtual Environment with Caching(tci_america_extraction)

on:
  workflow_dispatch: 

jobs:
  PYTHON_VENV_TCI:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Virtual Environment + Cache
        uses: actions/cache@v3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: venv-${{ runner.os }}-

      - name: Install System Dependencies (Poppler & Tesseract)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr

      - name: Set up Virtual Environment
        run: |
          if [ ! -d "venv" ]; then
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          else
            source venv/bin/activate
          fi

      - name: Verify Installations
        run: |
          source venv/bin/activate
          python --version
          pip list
          tesseract --version
          pdftotext -v

      - name: Run test for ollama
        run: |
            source venv/bin/activate
            ollama --version
            ollama serve
            ps aux | grep ollama

