name: tci_america_extract

on:  
  workflow_dispatch:


jobs:
  tci_america_extraction:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display System Information
      run: |
        cat /etc/os-release
        sudo -l
    
    - name: Configure Python Path
      run: echo "PYTHONPATH=${PYTHONPATH}:$(pwd)/src" >> $GITHUB_ENV

    - name: Import my action.yml for inheriting packages
      uses: ./.github/actions/install-dependencies
    
    - name: Verify Installations in main workflow
      run: |
        source venv/bin/activate
        python --version
        pip list
        tesseract --version
        pdftotext -v
        
    - name: run dummy python prgm
      run: |
        source venv/bin/activate
        python dummy.py

    # - name: Run the tci_america_extraction script.
    #   run: |
    #     python $(pwd)/src/manufacturer/tci_america/get_revisiondate_v4.py --dir 'revisionv4_test/pdffiles/' --log 'revisionv4_test/logs/logs1.log' --skip_pages '0'


